-- Clear existing data
TRUNCATE documents RESTART IDENTITY CASCADE;

-- Insert test documents with pre-computed embeddings
INSERT INTO documents (text, embedding, metadata) VALUES
(
    'How to make a delicious pasta carbonara',
    (SELECT array_agg(0.1)::vector(1536) FROM generate_series(1, 1536)),
    '{"type": "recipe", "cuisine": "italian", "difficulty": "medium"}'::jsonb
);

-- Note: In real usage, embeddings would be generated by OpenAI's API
-- These are simplified vectors for testing purposes only 
